untitled/apps/dashboard/urls.py
__author__ = 'Michał'

untitled/urls.py
from django.conf.urls import *
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from untitled.apps.dashboard.views import DashboardView, CarsView, CarDetailView, CarCreateView, CarUpdateView, CarDeleteView
from untitled.apps.dashboard.views import RepairCreateView ,ReplacementCreateView , RefuelingCreateView
from untitled.apps.dashboard.views import RepairDetailView , ReplacementDetailView, RefuelingDetailView
from untitled.apps.dashboard.views import RepairUpdateView, ReplacementUpdateView , RefuelingUpdateView
from untitled.apps.dashboard.views import ReDeleteView
from untitled.apps.account.models import Repair, Replacement , Refueling
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'untitled.views.home', name='home'),
    # url(r'^untitled/', include('untitled.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', DashboardView.as_view(), name='dashboard-home'),
    url(r'^cars/$', CarsView.as_view(), name='dashboard-cars'),
    url(r'^car/add/$', CarCreateView.as_view(), name='car-create'),
    url(r'^car/(?P<pk>[-\d]+)/detail/$', CarDetailView.as_view(), name='car-detail'),
    url(r'^car/(?P<pk>[-\d]+)/update/$', CarUpdateView.as_view(), name='car-update'),
    url(r'^car/(?P<pk>[-\d]+)/delete/$', CarDeleteView.as_view(), name='car-delete'),
    url(r'^car/(?P<pk>[-\d]+)/detail/repair/add/$', RepairCreateView.as_view(), name='repair-create'),
    url(r'^car/(?P<pk>[-\d]+)/detail/replacement/add/$', ReplacementCreateView.as_view(), name='replacement-create'),
    url(r'^car/(?P<pk>[-\d]+)/detail/refueling/add/$', RefuelingCreateView.as_view(), name='refueling-create'),

    url(r'^car/(?P<pk>[-\d]+)/detail/repair/$', RepairDetailView.as_view(), name='repair-detail'),
    url(r'^car/(?P<pk>[-\d]+)/detail/replacement/$', ReplacementDetailView.as_view(), name='replacement-detail'),
    url(r'^car/(?P<pk>[-\d]+)/detail/refueling/$', RefuelingDetailView.as_view(), name='refueling-detail'),

    url(r'^car/(?P<pk>[-\d]+)/detail/repair/update$', RepairUpdateView.as_view(), name='repair-update'),
    url(r'^car/(?P<pk>[-\d]+)/detail/replacement/update$', ReplacementUpdateView.as_view(), name='replacement-update'),
    url(r'^car/(?P<pk>[-\d]+)/detail/refueling/update$', RefuelingUpdateView.as_view(), name='refueling-update'),

    url(r'^car/(?P<pk>[-\d]+)/detail/repair/delete$', ReDeleteView.as_view(model=Repair), name='repair-delete'),
    url(r'^car/(?P<pk>[-\d]+)/detail/replacement/delete$', ReDeleteView.as_view(model=Replacement), name='replacement-delete'),
    url(r'^car/(?P<pk>[-\d]+)/detail/refueling/delete$', ReDeleteView.as_view(model=Refueling), name='refueling-delete'),


)\
              + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

untitled/apps/account/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from sorl.thumbnail import ImageField
from django.db.models import Sum

class Car(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name=_("name"))
    brand = models.CharField(max_length=255, verbose_name=_("brand") )
    model = models.CharField(max_length=255, verbose_name=_("model"))
    vintage = models.CharField(max_length=4,  verbose_name=_('vintage'))
    mileage = models.FloatField(verbose_name=_('mileage'))
    image_car = ImageField(upload_to='image', blank=True, null=True, verbose_name='image_car')
    created = models.DateTimeField(_('created'), auto_now_add=True)
    updated = models.DateTimeField(_('updated'), auto_now=True)

    class Meta:
        verbose_name = _("Car")
        verbose_name_plural = _("Cars")

    def __unicode__(self):
        return self.name

    def refuelings_cost(self):
        price_sum = self.refueling_set.aggregate(Sum('price'))
        sum = price_sum['price__sum']
        return sum



class RepairAndReplacement(models.Model):
    title = models.CharField(max_length=255, verbose_name=_("title"))
    description = models.CharField(max_length=255, verbose_name=_("description"), blank=True, null=True)
    car = models.ForeignKey('Car', verbose_name=_("car"))
    price = models.FloatField(verbose_name=_("price"))
    where = models.CharField(max_length=255, verbose_name=_("Where"),blank=True, null=True)
    created = models.DateTimeField(_('created'), auto_now_add=False,)

    class Meta:
        verbose_name = _("Repair and Replacement")
        abstract = True


class Repair(RepairAndReplacement):
    pass

class Replacement(RepairAndReplacement):
    pass

class Refueling(models.Model):
    Liters = models.FloatField(verbose_name=_("liters"))
    price = models.FloatField(verbose_name=_("price"))
    car = models.ForeignKey('Car', verbose_name=_("car"))
    created = models.DateTimeField(_('created'), auto_now_add=False)

untitled/apps/account/forms.py
from django import forms
from untitled.apps.account.models import Car, Repair, Replacement, Refueling


VINTAGE_CHOICES = (('',''),('1980','1980'), ('1981', '1981'), ('1982', '1982'), ('1983', '1983'), ('1984', '1984'), ('1985','1985'), ('1986', '1986'), ('1987', '1987'), ('1988', '1988'), ('1989', '1989'),
('1990','1990'), ('1991', '1991'), ('1992', '1992'), ('1993', '1993'), ('1994', '1994'), ('1995','1995'), ('1996', '1996'), ('1997', '1997'), ('1998', '1998'), ('1999', '1999'),
('2000','2000'), ('2001', '2001'), ('2002', '2002'), ('2003', '2003'), ('2004', '2004'), ('2005','2005'), ('2006', '2006'), ('2007', '2007'), ('2008', '2008'), ('2009', '2009'),
('2010','2000'), ('2011', '2011'), ('2012', '2012'), ('2013', '2013'), ('2014', '2014'),
)



class CarForm(forms.ModelForm):
    class Meta:
        model = Car

    vintage = forms.ChoiceField(choices=VINTAGE_CHOICES)

class RepairForm(forms.ModelForm):

    created = forms.DateTimeField(input_formats=['%m/%d/%Y %H:%M'])
    class Meta:
        model = Repair
        fields = ['title', 'description', 'where', 'price', 'created']

class ReplacementForm(forms.ModelForm):
    created = forms.DateTimeField(input_formats=['%m/%d/%Y %H:%M'])
    class Meta:
        model = Replacement
        fields = ['title', 'description', 'where', 'price', 'created']

class RefuelingForm(forms.ModelForm):
    created = forms.DateTimeField(input_formats=['%m/%d/%Y %H:%M'])
    class Meta:
        model = Refueling
        fields = ['Liters', 'price', 'created']

untitled/apps/dashboard/views.py
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.http import HttpResponseForbidden
from django.shortcuts import get_object_or_404
from untitled.apps.account.models import Car , Repair, Replacement, Refueling
from untitled.apps.account.forms import CarForm, RepairForm , ReplacementForm , RefuelingForm


class DashboardView(TemplateView):
    template_name = "dashboard/dashboard.html"
    active_tab = 'home'

      #Returns a dictionary representing the template context.
    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['active_tab'] = self.active_tab

        return context

class CarsView(ListView):
    template_name = "dashboard/cars.html"
    paginate_by = 10
    model = Car

    active_tab = 'cars'

    def __unicode__(self):
        return self.name

    def get_context_data(self, **kwargs):
        context = super(CarsView, self).get_context_data(**kwargs)
        context['active_tab'] = self.active_tab

        return context



class CarDetailView(DetailView):
    template_name = "dashboard/car_detail.html"
    model = Car

    def get_context_data(self, **kwargs):
        context = super(CarDetailView, self).get_context_data(**kwargs)
        name = get_object_or_404(Car, pk=self.kwargs.get('pk'))
        context['Repair'] = Repair.objects.filter(car=name)
        context['Replacement'] = Replacement.objects.filter(car=name)
        context['Refueling'] = Refueling.objects.filter(car=name)

        return context


class CarCreateView(CreateView):
    template_name = "dashboard/car_form.html"
    model = Car
    form_class = CarForm

    def get_success_url(self):
        return reverse("dashboard-cars")

    def upload_pic(request):
        if request.method == 'POST':
            form = CarForm(request.POST, request.FILES)
            if form.is_valid():
                m = Car.objects.get(pk=Car.pk)
                m.image_car = form.cleaned_data['image_car']
                m.save()

                return HttpResponse('image upload success')
        return HttpResponseForbidden('allowed only via POST')



class CarDeleteView(DeleteView):
    model = Car
    template_name = "dashboard/car_delete.html"

    def get_success_url(self):
        return reverse("dashboard-cars")

class CarUpdateView(UpdateView):
    model = Car
    template_name = "dashboard/car_form.html"

    def get_success_url(self):
        return reverse("dashboard-cars")

class Re(object):
    def get_car(self):
        return get_object_or_404(Car, pk=self.kwargs.get('pk'))

    def form_valid(self, form):
        form.instance.car = self.get_car()
        return super(Re, self).form_valid(form)

    def get_success_url(self):
        return reverse("car-detail" , args=self.kwargs.get('pk'))



class RepairCreateView(Re, CreateView):
    model = Repair
    form_class = RepairForm
    template_name = "dashboard/car_detail/repair_form.html"

class ReplacementCreateView(Re, CreateView):
    model = Replacement
    form_class = ReplacementForm
    template_name = "dashboard/car_detail/replacement_form.html"

class RefuelingCreateView(Re, CreateView):
    model = Refueling
    form_class = RefuelingForm
    template_name = "dashboard/car_detail/refueling_form.html"




class RepairDetailView(DetailView):
    model = Repair
    template_name = "dashboard/car_detail/repair_detail.html"

class ReplacementDetailView(DetailView):
    model = Replacement
    template_name = "dashboard/car_detail/replacement_detail.html"

class RefuelingDetailView(DetailView):
    model = Refueling
    template_name = "dashboard/car_detail/refueling_detail.html"



class RepairUpdateView(Re, UpdateView):
    model = Repair
    form_class = RepairForm
    template_name = "dashboard/car_detail/repair_form.html"

class ReplacementUpdateView(Re, UpdateView):
    model = Replacement
    form_class = ReplacementForm
    template_name = "dashboard/car_detail/replacement_form.html"

class RefuelingUpdateView(Re, UpdateView):
    model = Refueling
    form_class = RefuelingForm
    template_name = "dashboard/car_detail/refueling_form.html"



class ReDeleteView(DeleteView):

    template_name = "dashboard/car_detail/re_delete.html"

    def get_success_url(self):
        return reverse("car-detail", args=(self.object.car.id,))

untitled/templates/dashboard/car_detail/re_delete.html
{% extends 'dashboard/car_detail.html' %}
{% load i18n %}

{% block left_column %}
    <div class="col-md-8">
         <h3 class="title">{% trans "Delete Car" %} {{ car.name }}</h3>

        <div class="alert alert-error">
            <h4>{% trans "Are you sure?" %}</h4>

        </div>


        <form action="" method="post">
            {% csrf_token %}
            <div class="submit-row">
                <input type="submit" value="{% trans 'Delete' %}" class="btn btn-danger" />
                <a class="btn btn-default" href="{% url "car-detail" object.car.pk %}">{% trans "Cancel" %}</a>
            </div>
        </form>
    </div>
{% endblock %}

untitled/templates/dashboard/car_detail/refueling_detail.html
{% extends 'index.html' %}

{% load i18n %}

{% block left_column %}
    <div class="col-md-8">

    <h2>{{ object.title }}</h2>

    <div class="alert alert-info">

        <dl class="dl-horizontal-sidebar">

            <dt>{% trans "Liters" %}:</dt>
            <dd>{{ object.Liters }}</dd>
            <dt>{% trans "price" %}:</dt>
            <dd>{{ object.price }}</dd>
            <dt>{% trans "Created" %}:</dt>
            <dd>{{ object.created }}</dd>

        </dl>
    </div>

    <a class="btn" href="{% url "car-detail" object.car.pk %}">{% trans "Back" %}</a>
    </div>
{% endblock %}

untitled/templates/dashboard/car_detail/refueling_form.html
{% extends 'index.html' %}
{% load as_horizontal_form from bootstrap %}
{% load i18n %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block js %}
    {{ block.super }}

{#    	<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>#}
{#		<script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>#}
		<script  src="{{ STATIC_URL }}css/jquery-ui-timepicker-addon.css"></script>
		<script  src="{{ STATIC_URL }}js/jquery-ui-timepicker-addon.js"></script>

    <script type="text/javascript">
        $(function() {
            $( '#id_created' ).attr('autocomplete', 'off');
            $( "#id_created" ).datetimepicker();
        });
    </script>
{% endblock %}

{% block left_column %}
    <div class="col-md-6">
         <h3 class="title">{{ action }}</h3>
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <fieldset>
                    {{ form|as_horizontal_form }}
                </fieldset>
                <div class="submit-row">
                    <input type="submit" value="{% trans 'Save' %}" class="btn btn-primary" />
                </div>
            </form>
    </div>
{% endblock %}

untitled/templates/dashboard/car_detail/repair_detail.html
{% extends 'index.html' %}

{% load i18n %}

{% block left_column %}
    <div class="col-md-8">

    <h2>{{ object.title }}</h2>

    <div class="alert alert-info">

        <dl class="dl-horizontal-sidebar">
            <dt>{% trans "description" %}:</dt>
            <dd>{{ object.description }}</dd>
            <dt>{% trans "Pleace" %}:</dt>
            <dd>{{ object.where }}</dd>
            <dt>{% trans "price" %}:</dt>
            <dd>{{ object.price }}</dd>
            <dt>{% trans "Created" %}:</dt>
            <dd>{{ object.created }}</dd>

        </dl>
    </div>

    <a class="btn" href="{% url "car-detail" object.car.pk %}">{% trans "Back" %}</a>
    </div>
{% endblock %}

untitled/templates/dashboard/car_detail/repair_form.html
{% extends 'index.html' %}
{% load as_horizontal_form from bootstrap %}
{% load i18n %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block js %}
    {{ block.super }}

{#    	<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>#}
{#		<script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>#}
			<script  src="{{ STATIC_URL }}css/jquery-ui-timepicker-addon.css"></script>
		<script  src="{{ STATIC_URL }}js/jquery-ui-timepicker-addon.js"></script>

    <script type="text/javascript">
        $(function() {
            $( '#id_created' ).attr('autocomplete', 'off');
            $( "#id_created" ).datetimepicker();
        });
    </script>
{% endblock %}

{% block left_column %}
    <div class="col-md-6">
         <h3 class="title">{{ action }}</h3>
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <fieldset>
                    {{ form|as_horizontal_form }}
                </fieldset>
                <div class="submit-row">
                    <input type="submit" value="{% trans 'Save' %}" class="btn btn-primary" />
                </div>
            </form>
    </div>
{% endblock %}

untitled/templates/dashboard/car_detail/replacement_detail.html
{% extends 'index.html' %}

{% load i18n %}

{% block left_column %}
    <div class="col-md-8">

    <h2>{{ object.title }}</h2>

    <div class="alert alert-info">

        <dl class="dl-horizontal-sidebar">
            <dt>{% trans "description" %}:</dt>
            <dd>{{ object.description }}</dd>
            <dt>{% trans "Pleace" %}:</dt>
            <dd>{{ object.where }}</dd>
            <dt>{% trans "price" %}:</dt>
            <dd>{{ object.price }}</dd>
            <dt>{% trans "Created" %}:</dt>
            <dd>{{ object.created }}</dd>

        </dl>
    </div>

    <a class="btn" href="{% url "car-detail" object.car.pk %}">{% trans "Back" %}</a>
    </div>
{% endblock %}

untitled/templates/dashboard/car_detail/replacement_form.html
{% extends 'index.html' %}
{% load as_horizontal_form from bootstrap %}
{% load i18n %}

{% block css %}
    {{ block.super }}
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
{% endblock %}

{% block js %}
    {{ block.super }}

{#    	<script type="text/javascript" src="http://code.jquery.com/jquery-1.10.1.min.js"></script>#}
{#		<script type="text/javascript" src="http://code.jquery.com/ui/1.10.3/jquery-ui.min.js"></script>#}
			<script  src="{{ STATIC_URL }}css/jquery-ui-timepicker-addon.css"></script>
		<script  src="{{ STATIC_URL }}js/jquery-ui-timepicker-addon.js"></script>

    <script type="text/javascript">
        $(function() {
            $( '#id_created' ).attr('autocomplete', 'off');
            $( "#id_created" ).datetimepicker();
        });
    </script>
{% endblock %}

{% block left_column %}
    <div class="col-md-6">
         <h3 class="title">{{ action }}</h3>
            <form action="" method="post" enctype="multipart/form-data" class="form-horizontal">
                {% csrf_token %}
                <fieldset>
                    {{ form|as_horizontal_form }}
                </fieldset>
                <div class="submit-row">
                    <input type="submit" value="{% trans 'Save' %}" class="btn btn-primary" />
                </div>
            </form>
    </div>
{% endblock %}